import type { Product, ProductSpec } from "@/content/products";

/**
 * Hunting shotguns and cartridges using the photographs already in the Issawi catalog.
 * These are sample listings. They are not confirmed Syoufi Hunting stock.
 */
function spec(en: string, ar: string, value: string): ProductSpec {
  return { label: { en, ar }, value };
}

const shotgun = "A 12-gauge hunting shotgun from the sample catalog. The photograph is the Issawi product image. Ask for the price.";
const shotgunAr = "بندقية صيد عيار 12 من كتالوج العيّنات. الصورة من منتجات العيسوي. استفسر عن السعر.";

export const armsCatalog: Product[] = [
  {
    id: "aselkon-x3-dark-black",
    slug: "aselkon-x3-dark-black",
    name: { en: "Aselkon X3 Dark Black", ar: "أسلكون X3 Dark Black" },
    brand: "Aselkon",
    category: "rifles",
    images: ["/images/products/aselkon-x3-dark-black.jpg"],
    placeholder: "shotgun",
    featured: true,
    isDemo: true,
    sample: true,
    description: { en: shotgun, ar: shotgunAr },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("System", "النظام", "Inertia"),
    ],
  },
  {
    id: "aselkon-x5-bronze-pure",
    slug: "aselkon-x5-bronze-pure",
    name: { en: "Aselkon X5 Bronze Pure", ar: "أسلكون X5 Bronze Pure" },
    brand: "Aselkon",
    category: "rifles",
    images: ["/images/products/aselkon-x5-bronze-pure.jpg"],
    placeholder: "shotgun",
    featured: false,
    isDemo: true,
    sample: true,
    description: { en: shotgun, ar: shotgunAr },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("System", "النظام", "Inertia"),
    ],
  },
  {
    id: "radikal-sax-2",
    slug: "radikal-sax-2",
    name: { en: "Radikal SAX-2", ar: "راديكال SAX-2" },
    brand: "Radikal",
    category: "rifles",
    images: ["/images/products/radikal-sax-2.jpg"],
    placeholder: "shotgun",
    featured: true,
    isDemo: true,
    sample: true,
    description: { en: shotgun, ar: shotgunAr },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("System", "النظام", "Inertia"),
    ],
  },
  {
    id: "radikal-sax-2-limited",
    slug: "radikal-sax-2-limited",
    name: { en: "Radikal SAX-2 Limited Edition", ar: "راديكال SAX-2 Limited Edition" },
    brand: "Radikal",
    category: "rifles",
    images: ["/images/products/radikal-sax-2-limited.webp"],
    placeholder: "shotgun",
    featured: false,
    isDemo: true,
    sample: true,
    description: { en: shotgun, ar: shotgunAr },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("System", "النظام", "Inertia"),
    ],
  },
  {
    id: "bme-express-c12-28",
    slug: "bme-express-c12-28",
    name: { en: "BME Express C12 28g", ar: "BME Express C12 ‏28غ" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/express-c12-28.jpg"],
    placeholder: "cartridge",
    featured: true,
    isDemo: true,
    sample: true,
    description: {
      en: "BME Express 12-gauge, 28 gram hunting cartridges. The box photograph is from the Issawi catalog and shows shot sizes 8, 9, and 10. Ask for the price.",
      ar: "خراطيش صيد BME Express عيار 12 ووزن 28 غرام. صورة العلبة من كتالوج العيسوي وتظهر أرقام الخرطوش 8 و9 و10. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "28 g"),
      spec("Shot size", "رقم الخرطوش", "8 / 9 / 10"),
      spec("Maker", "الصانع", "BME / Brescia Middle East"),
    ],
  },
  {
    id: "bme-super-c12-32",
    slug: "bme-super-c12-32",
    name: { en: "BME Super C12 32g", ar: "BME Super C12 ‏32غ" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/super-c12-32.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "BME Super 12-gauge, 32 gram hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد BME Super عيار 12 ووزن 32 غرام. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "32 g"),
      spec("Maker", "الصانع", "BME / Brescia Middle East"),
    ],
  },
  {
    id: "bme-standard-c12-28",
    slug: "bme-standard-c12-28",
    name: { en: "BME Standard C12 28g", ar: "BME Standard C12 ‏28غ" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/standard-c12-28.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "BME Standard 12-gauge, 28 gram hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش BME Standard عيار 12 ووزن 28 غرام للصيد. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "28 g"),
    ],
  },
  {
    id: "bme-oro-c12-29",
    slug: "bme-oro-c12-29",
    name: { en: "BME Oro C12 29g", ar: "BME Oro C12 ‏29غ" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/oro-c12-29.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "BME Oro 12-gauge, 29 gram hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد BME Oro عيار 12 ووزن 29 غرام. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "29 g"),
    ],
  },
  {
    id: "bme-slug-c12",
    slug: "bme-slug-c12",
    name: { en: "BME Slug C12", ar: "BME Slug C12" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/slug-c12.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "BME 12-gauge slug cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش سلاق BME عيار 12. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Type", "النوع", "Slug"),
    ],
  },
  {
    id: "bme-junior-c12-26",
    slug: "bme-junior-c12-26",
    name: { en: "BME Junior C12 26g", ar: "BME Junior C12 ‏26غ" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/junior-c12-26.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "BME Junior 12-gauge, 26 gram cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش BME Junior عيار 12 ووزن 26 غرام. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "26 g"),
    ],
  },
  {
    id: "bme-millionaire-c12-26",
    slug: "bme-millionaire-c12-26",
    name: { en: "BME Millionaire C12 26g", ar: "BME Millionaire C12 ‏26غ" },
    brand: "BME",
    category: "cartridges",
    images: ["/images/products/bme/millionaire-c12-26.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "BME Millionaire 12-gauge, 26 gram cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش BME Millionaire عيار 12 ووزن 26 غرام. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "26 g"),
    ],
  },
  {
    id: "saga-field",
    slug: "saga-field",
    name: { en: "Saga Field 12 GA", ar: "Saga Field عيار 12" },
    brand: "Saga",
    category: "cartridges",
    images: ["/images/products/saga/field.jpg"],
    placeholder: "cartridge",
    featured: true,
    isDemo: true,
    sample: true,
    description: {
      en: "Saga Field 12-gauge hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد Saga Field عيار 12. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Line", "السلسلة", "Field"),
      spec("Maker", "الصانع", "Saga"),
    ],
  },
  {
    id: "saga-export",
    slug: "saga-export",
    name: { en: "Saga Export 12 GA", ar: "Saga Export عيار 12" },
    brand: "Saga",
    category: "cartridges",
    images: ["/images/products/saga/export.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "Saga Export 12-gauge hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد Saga Export عيار 12. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Line", "السلسلة", "Export"),
    ],
  },
  {
    id: "saga-high-speed",
    slug: "saga-high-speed",
    name: { en: "Saga High Speed 12 GA", ar: "Saga High Speed عيار 12" },
    brand: "Saga",
    category: "cartridges",
    images: ["/images/products/saga/highspeed.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "Saga High Speed 12-gauge hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد Saga High Speed عيار 12. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Line", "السلسلة", "High Speed"),
    ],
  },
  {
    id: "saga-heavy-34",
    slug: "saga-heavy-34",
    name: { en: "Saga Heavy 34", ar: "Saga Heavy 34" },
    brand: "Saga",
    category: "cartridges",
    images: ["/images/products/saga/heavy-34.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "Saga Heavy 34, a 12-gauge hunting load. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد Saga Heavy 34 بعيار 12. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Load", "الحمل", "34 g"),
    ],
  },
  {
    id: "saga-rabbit",
    slug: "saga-rabbit",
    name: { en: "Saga Rabbit", ar: "Saga Rabbit" },
    brand: "Saga",
    category: "cartridges",
    images: ["/images/products/saga/rabbit.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "Saga Rabbit hunting cartridges. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش صيد Saga Rabbit. الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [spec("Line", "السلسلة", "Rabbit"), spec("Maker", "الصانع", "Saga")],
  },
  {
    id: "saga-buck",
    slug: "saga-buck",
    name: { en: "Saga Buck 12 GA", ar: "Saga Buck عيار 12" },
    brand: "Saga",
    category: "cartridges",
    images: ["/images/products/saga/buck.jpg"],
    placeholder: "cartridge",
    featured: false,
    isDemo: true,
    sample: true,
    description: {
      en: "Saga Buck 12-gauge buckshot. Photograph from the Issawi catalog. Ask for the price.",
      ar: "خراطيش Saga Buck عيار 12 (خرز كبير). الصورة من كتالوج العيسوي. استفسر عن السعر.",
    },
    specs: [
      spec("Gauge", "العيار", "12"),
      spec("Type", "النوع", "Buckshot"),
    ],
  },
];
