import type { Product, ProductSpec } from "@/content/products";

/**
 * Sample catalog sourced from public manufacturer pages.
 * These are not confirmed Syoufi Hunting stock, prices, or warranties.
 * Photographs are the manufacturers' images. Reuse permission is unverified.
 * Entries with an empty images array stay out of the storefront.
 */
function spec(en: string, ar: string, value: string): ProductSpec {
  return { label: { en, ar }, value };
}

export const sampleCatalog: Product[] = [
  {
    id: "vortex-diamondback-hd-10x42",
    slug: "vortex-diamondback-hd-10x42",
    name: { en: "Vortex Diamondback HD 10x42", ar: "منظار Vortex Diamondback HD 10x42" },
    brand: "Vortex",
    category: "optics",
    images: ["/images/products/vortex-diamondback-hd-10x42.jpg"],
    placeholder: "optics",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://vortexoptics.com/vortex-diamondback-hd-10x42-binocular.html",
    description: {
      en: "Roof-prism binocular listed by Vortex for hunting and wildlife observation. Specifications below are from the manufacturer page.",
      ar: "منظار بمنشور سقف، وتدرجه فورتكس للصيد ومراقبة الحياة البرية. المواصفات أدناه من صفحة الشركة المصنّعة.",
    },
    specs: [
      spec("Magnification", "التكبير", "10x"),
      spec("Objective lens", "قطر العدسة", "42 mm"),
      spec("Eye relief", "راحة العين", "15.0 mm"),
      spec("Angular field of view", "مجال الرؤية الزاوي", "6.3°"),
      spec("Linear field of view", "مجال الرؤية الخطي", "330 ft at 1,000 yd"),
      spec("Close focus", "أقرب تركيز", "5.0 ft"),
      spec("Interpupillary distance", "المسافة بين الحدقتين", "55–73 mm"),
      spec("Height", "الارتفاع", "5.7 in"),
      spec("Width", "العرض", "5.1 in"),
      spec("Weight", "الوزن", "21.3 oz"),
    ],
  },
  {
    id: "nikon-prostaff-p7-8x42",
    slug: "nikon-prostaff-p7-8x42",
    name: { en: "Nikon PROSTAFF P7 8x42", ar: "منظار Nikon PROSTAFF P7 8x42" },
    brand: "Nikon",
    category: "optics",
    images: ["/images/products/nikon-prostaff-p7-8x42.jpg"],
    placeholder: "optics",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://imaging.nikon.com/sport-optics/lineup/binoculars/prostaff/prostaff_p7_x42/",
    description: {
      en: "Roof-prism binocular. Nikon lists it as waterproof to 1 m for 10 minutes and fog-free. Not designed for underwater use.",
      ar: "منظار بمنشور سقف. تذكر نيكون أنه مقاوم للماء حتى متر واحد لمدة 10 دقائق ومضاد للضباب. غير مخصص للاستخدام تحت الماء.",
    },
    specs: [
      spec("Magnification", "التكبير", "8x"),
      spec("Objective lens", "قطر العدسة", "42 mm"),
      spec("Real angular field of view", "مجال الرؤية الزاوي الحقيقي", "7.2°"),
      spec("Apparent angular field of view", "مجال الرؤية الظاهري", "53.4° (ISO 14132-1:2002)"),
      spec("Field of view at 1,000 m", "مجال الرؤية عند 1000 م", "126 m"),
      spec("Exit pupil", "قطر بؤبؤ الخروج", "5.3 mm"),
      spec("Eye relief", "راحة العين", "20.2 mm"),
      spec("Close focus", "أقرب تركيز", "3.0 m"),
      spec("Length", "الطول", "152 mm"),
      spec("Width", "العرض", "130 mm"),
      spec("Depth", "السماكة", "55 mm"),
      spec("Weight", "الوزن", "590 g"),
      spec("Interpupillary distance", "المسافة بين الحدقتين", "56–72 mm"),
    ],
  },
  {
    id: "streamlight-protac-hl-x",
    slug: "streamlight-protac-hl-x",
    name: { en: "Streamlight ProTac HL-X", ar: "كشاف Streamlight ProTac HL-X" },
    brand: "Streamlight",
    category: "lighting",
    images: ["/images/products/streamlight-protac-hl-x.jpg"],
    placeholder: "flashlight",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.streamlight.com/products/detail/protac-hl-x",
    description: {
      en: "Handheld flashlight sold in a rechargeable configuration with an SL-B26 battery pack, or with two CR123A batteries. Output depends on the battery.",
      ar: "كشاف يدوي يُباع ببطارية SL-B26 قابلة للشحن، أو ببطاريتين CR123A. شدة الإضاءة تختلف حسب البطارية.",
    },
    specs: [
      spec("High output, SL-B26", "الإضاءة العالية مع SL-B26", "1,300 lumens; 35,000 candela; 374 m; 1.5 hours"),
      spec("Medium output, SL-B26", "الإضاءة المتوسطة مع SL-B26", "420 lumens; 11,000 candela; 210 m; 3.75 hours"),
      spec("Low output, SL-B26", "الإضاءة المنخفضة مع SL-B26", "70 lumens; 1,800 candela; 85 m; 25 hours"),
      spec("High output, two CR123A", "الإضاءة العالية مع CR123A", "1,000 lumens"),
      spec("Medium output, two CR123A", "الإضاءة المتوسطة مع CR123A", "400 lumens"),
      spec("Low output, two CR123A", "الإضاءة المنخفضة مع CR123A", "65 lumens"),
    ],
  },
  {
    id: "black-diamond-spot-400-r",
    slug: "black-diamond-spot-400-r",
    name: { en: "Black Diamond Spot 400-R, Graphite", ar: "مصباح رأس Black Diamond Spot 400-R، Graphite" },
    brand: "Black Diamond",
    category: "lighting",
    images: ["/images/products/black-diamond-spot-400-r-graphite.webp"],
    placeholder: "flashlight",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://blackdiamondequipment.com/products/spot-400-r-rechargeable-headlamp",
    description: {
      en: "Rechargeable headlamp with a micro-USB port and an integrated 1500 mAh lithium-ion battery. Black Diamond rates the housing IP67.",
      ar: "مصباح رأس قابل للشحن بمنفذ micro-USB وبطارية ليثيوم أيون مدمجة سعتها 1500 مللي أمبير. تقييم الهيكل لدى بلاك دايموند هو IP67.",
    },
    specs: [
      spec("Lumens", "اللومن", "High 400; medium 200; low 6"),
      spec("Max burn time", "أقصى مدة تشغيل", "High 4 hours; medium 8 hours; low 225"),
      spec("Max distance", "أقصى مسافة", "High 100 m; medium 60 m; low 12 m"),
      spec("Weight", "الوزن", "86 g"),
      spec("Battery", "البطارية", "1500 mAh Li-ion"),
      spec("Water rating", "مقاومة الماء", "IP67, tested at 1.0 m for 30 minutes"),
    ],
  },
  {
    id: "biolite-alpenglow-500",
    slug: "biolite-alpenglow-500",
    name: { en: "BioLite AlpenGlow 500", ar: "فانوس BioLite AlpenGlow 500" },
    brand: "BioLite",
    category: "lighting",
    images: ["/images/products/biolite-alpenglow-500.png"],
    placeholder: "flashlight",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.bioliteenergy.com/products/alpenglow-500",
    description: {
      en: "Rechargeable multicolor camping lantern. The manufacturer lists a micro-USB charge and separate high and low outputs.",
      ar: "فانوس تخييم متعدد الألوان وقابل للشحن. تذكر الشركة المصنّعة الشحن عبر micro-USB ووضعَي إضاءة عالٍ ومنخفض.",
    },
    specs: [
      spec("Lumens", "اللومن", "500 high; 5 low"),
      spec("Burn time", "مدة التشغيل", "5 hours high; up to 200 hours low"),
      spec("Charge time", "مدة الشحن", "3 hours at 5V/2A micro-USB"),
      spec("Water resistance", "مقاومة الماء", "IPX4"),
      spec("Color rendering", "تجسيد اللون", "ChromaReal LED, CRI 90"),
      spec("Dimensions", "الأبعاد", "5.4 x 3.8 in (136 x 97 mm)"),
    ],
  },
  {
    id: "biolite-alpenglow-mini",
    slug: "biolite-alpenglow-mini",
    name: { en: "BioLite AlpenGlow Mini", ar: "فانوس BioLite AlpenGlow Mini" },
    brand: "BioLite",
    category: "lighting",
    images: ["/images/products/biolite-alpenglow-mini.png"],
    placeholder: "flashlight",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.bioliteenergy.com/products/alpenglow-mini",
    description: {
      en: "Smaller rechargeable lantern in the same series, with a USB-C input. Specifications are from the BioLite product page.",
      ar: "فانوس أصغر قابل للشحن من السلسلة نفسها، ومدخله USB-C. المواصفات من صفحة بايولايت.",
    },
    specs: [
      spec("Lumens", "اللومن", "150 high; 5 low"),
      spec("Runtime", "مدة التشغيل", "5 hours high; 40 hours low"),
      spec("Recharge time", "مدة الشحن", "3 hours"),
      spec("Weather resistance", "مقاومة الطقس", "IPX4"),
      spec("Weight", "الوزن", "98 g"),
      spec("Battery", "البطارية", "1,000 mAh Li-ion (3.7 Wh)"),
      spec("Dimensions", "الأبعاد", "75 mm x 51 mm"),
      spec("Input", "مدخل الشحن", "USB-C"),
    ],
  },
  {
    id: "suunto-a-10-nh",
    slug: "suunto-a-10-nh",
    name: { en: "Suunto A-10 NH", ar: "بوصلة Suunto A-10 NH" },
    brand: "Suunto",
    category: "optics",
    images: ["/images/products/suunto-a-10-nh.webp"],
    placeholder: "optics",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://us.suunto.com/products/suunto-a-10-nh-compass",
    description: {
      en: "Baseplate compass balanced for the northern hemisphere, with a fixed declination scale and no battery. Suunto states it is made in Finland.",
      ar: "بوصلة قاعدة ميزان إبرتها لنصف الكرة الشمالي، بمقياس انحراف ثابت ومن دون بطارية. تذكر سونتو أنها مصنوعة في فنلندا.",
    },
    specs: [
      spec("Dimensions", "الأبعاد", "56 x 104 x 10 mm"),
      spec("Weight", "الوزن", "30 g"),
      spec("Accuracy", "الدقة", "2.5°"),
      spec("Resolution", "الدقة التدريجية", "2°"),
      spec("Declination", "الانحراف المغناطيسي", "Fixed scale"),
      spec("Needle", "الإبرة", "High-grade steel, jewel bearing, liquid-filled capsule"),
      spec("Operating temperature", "حرارة التشغيل", "−30°C to +60°C"),
    ],
  },
  {
    id: "merrell-moab-3-mid-waterproof",
    slug: "merrell-moab-3-mid-waterproof",
    name: { en: "Merrell Moab 3 Mid Waterproof, Black/Beluga", ar: "حذاء Merrell Moab 3 Mid Waterproof، Black/Beluga" },
    brand: "Merrell",
    category: "clothing",
    images: ["/images/products/merrell-moab-3-mid-black-beluga.jpg"],
    placeholder: "outfit",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.merrell.com/US/en/moab-3-mid-waterproof/52470M.html",
    description: {
      en: "Men's mid hiking boot with a waterproof membrane, pig-suede and mesh upper, and a Vibram TC5+ outsole. The half-pair weight is the figure Merrell publishes for this model.",
      ar: "حذاء مشي رجالي متوسط الارتفاع بغشاء ضد الماء، ووجه من الشامواه الشبكي، ونعل Vibram TC5+. وزن النصف هو الرقم الذي تنشره ميريل لهذا الموديل.",
    },
    specs: [
      spec("Drop", "فرق الارتفاع", "11.5 mm"),
      spec("Lug depth", "عمق النتوءات", "5 mm"),
      spec("Half-pair weight", "وزن نصف الزوج", "495 g"),
      spec("Outsole", "النعل الخارجي", "Vibram TC5+"),
      spec("Upper", "الوجه", "Pig suede leather and mesh, waterproof membrane"),
    ],
  },
  {
    id: "sea-to-summit-ultra-sil-nano-poncho",
    slug: "sea-to-summit-ultra-sil-nano-poncho",
    name: { en: "Sea to Summit Ultra-Sil Nano Poncho, Lime", ar: "معطف مطر Sea to Summit Ultra-Sil Nano، Lime" },
    brand: "Sea to Summit",
    category: "clothing",
    images: ["/images/products/sea-to-summit-ultra-sil-nano-poncho-lime.webp"],
    placeholder: "jacket",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://seatosummit.eu/en-lu/products/ultra-sil-nano-poncho",
    description: {
      en: "Poncho made from 15D Ultra-Sil Nano fabric. Sea to Summit lists it for rain protection and as a pack cover, and states that it is waterproof.",
      ar: "معطف مطر من قماش Ultra-Sil Nano قياس 15D. تذكر سي تو ساميت أنه للحماية من المطر ولتغطية الحقيبة، وأنه مقاوم للماء.",
    },
    specs: [
      spec("Weight", "الوزن", "145 g"),
      spec("Dimensions", "الأبعاد", "140 x 118 cm"),
      spec("Packed size", "الحجم مطويًا", "6.5 x 13.5 cm"),
      spec("Fabric", "القماش", "15D Ultra-Sil Nano"),
    ],
  },
  {
    id: "mechanix-original-black",
    slug: "mechanix-original-black",
    name: { en: "Mechanix The Original, black", ar: "قفازات Mechanix The Original، أسود" },
    brand: "Mechanix Wear",
    category: "clothing",
    images: ["/images/products/mechanix-original-black.jpg"],
    placeholder: "outfit",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.mechanix.com/ca-en/all-work-gloves/MG-05.html",
    description: {
      en: "Work glove, style DTC-MG-05-013. Mechanix describes a 0.8 mm synthetic-leather palm, a CoolPlus mesh back, and a machine-washable construction.",
      ar: "قفاز عمل، الرمز DTC-MG-05-013. تصف ميكانيكس راحة من جلد صناعي بسماكة 0.8 مم، وظهرًا من شبكة CoolPlus، وبنية قابلة للغسل في الغسالة.",
    },
    specs: [
      spec("Palm", "الراحة", "0.8 mm synthetic leather, touchscreen capable"),
      spec("Back of hand", "ظهر اليد", "CoolPlus woven mesh"),
      spec("Closure", "الإغلاق", "Thermoplastic rubber hook-and-loop"),
      spec("Care", "العناية", "Machine washable"),
    ],
  },
  {
    id: "outdoor-research-seattle-rain-hat",
    slug: "outdoor-research-seattle-rain-hat",
    name: { en: "Outdoor Research Seattle Rain Hat, Ascent Blue/Skyline", ar: "قبعة Outdoor Research Seattle Rain Hat، Ascent Blue/Skyline" },
    brand: "Outdoor Research",
    category: "clothing",
    images: ["/images/products/outdoor-research-seattle-rain-hat.webp"],
    placeholder: "outfit",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.outdoorresearch.com/products/seattle-rain-hat-322290",
    description: {
      en: "GORE-TEX rain hat, style 322290. Outdoor Research lists a fully seam-taped crown and UPF 50+ sun protection.",
      ar: "قبعة مطر من غور-تكس، الرمز 322290. تذكر أوتدور ريسيرش تاجًا ملصوق الدروز وحماية من الشمس UPF 50+.",
    },
    specs: [
      spec("Weight", "الوزن", "87 g"),
      spec("Fabric", "القماش", "GORE-TEX 2L recycled nylon, 70D crown"),
      spec("Brim", "الحافة", "3 in front, 3.75 in back"),
      spec("Sun rating", "الحماية من الشمس", "UPF 50+"),
      spec("Style number", "رقم الموديل", "322290"),
    ],
  },
  {
    id: "helinox-chair-one",
    slug: "helinox-chair-one",
    name: { en: "Helinox Chair One, black", ar: "كرسي Helinox Chair One، أسود" },
    brand: "Helinox",
    category: "camping",
    images: ["/images/products/helinox-chair-one-black.jpg"],
    placeholder: "chair",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://helinox.com/products/chair-one",
    description: {
      en: "Folding camp chair with a DAC TH72M aluminum frame. Capacity and dimensions below are the assembled figures on the Helinox specifications table.",
      ar: "كرسي تخييم قابل للطي بهيكل ألمنيوم DAC TH72M. الحمولة والأبعاد أدناه هي أرقام الطاولة لدى هيلينوكس للكرسي مفتوحًا.",
    },
    specs: [
      spec("Capacity", "الحمولة", "320 lb (145 kg)"),
      spec("Seat height", "ارتفاع المقعد", "25.5 in (65 cm)"),
      spec("Seat width", "عرض المقعد", "20.5 in (52.5 cm)"),
      spec("Seat depth", "عمق المقعد", "20 in (51 cm)"),
      spec("Assembled weight", "الوزن مفتوحًا", "1 lb 15 oz (893 g)"),
      spec("Packed weight", "الوزن مطويًا", "2 lb 2 oz (965 g)"),
    ],
  },
  {
    id: "msr-hubba-hubba-lt-2",
    slug: "msr-hubba-hubba-lt-2",
    name: { en: "MSR Hubba Hubba LT 2", ar: "خيمة MSR Hubba Hubba LT 2" },
    brand: "MSR",
    category: "camping",
    images: ["/images/products/msr-hubba-hubba-lt-2.webp"],
    placeholder: "outfit",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://www.msrgear.com/tents/backpacking-tents/hubba-hubba-lt-2-person-backpacking-tent/13937.html",
    description: {
      en: "Two-person backpacking tent. MSR describes a rectangular floor and a mostly micromesh body.",
      ar: "خيمة لشخصين للرحلات. تصف MSR أرضية مستطيلة وجسمًا معظمه من الشبكة الدقيقة.",
    },
    specs: [
      spec("Minimum weight", "الوزن الأدنى", "3 lb (1.36 kg)"),
      spec("Packaged weight", "وزن العبوة", "3 lb 6 oz (1.54 kg)"),
      spec("Floor area", "مساحة الأرضية", "32 sq ft (2.95 sq m)"),
      spec("Vestibule area", "مساحة الدهليز", "16 sq ft (1.48 sq m)"),
      spec("Interior peak height", "ارتفاع القمة من الداخل", "40 in (102 cm)"),
    ],
  },
  {
    id: "sea-to-summit-trek-down-minus-1",
    slug: "sea-to-summit-trek-down-minus-1",
    name: { en: "Sea to Summit Trek Down, −1°C regular", ar: "كيس نوم Sea to Summit Trek Down، −1°م مقاس عادي" },
    brand: "Sea to Summit",
    category: "camping",
    images: ["/images/products/sea-to-summit-trek-down-minus-1c.webp"],
    placeholder: "outfit",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://seatosummit.com.au/products/trek-down-sleeping-bag",
    description: {
      en: "Down sleeping bag. Figures are the −1°C regular column on the Sea to Summit tech table. The page rates temperature with ISO lower and women's ISO comfort values.",
      ar: "كيس نوم من الزغب. الأرقام من عمود −1°م بالمقاس العادي في جدول سي تو ساميت. الصفحة تذكر حد ISO الأدنى وراحة ISO للنساء.",
    },
    specs: [
      spec("Weight", "الوزن", "1,119 g"),
      spec("Fill weight", "وزن الحشوة", "380 g"),
      spec("Fill", "الحشوة", "80/20 duck down"),
      spec("Compressed volume", "الحجم مضغوطًا", "8.2 L"),
      spec("ISO lower rating", "حد ISO الأدنى", "−1°C"),
      spec("ISO comfort, women", "راحة ISO للنساء", "3°C"),
      spec("Recommended user height", "الطول المقترح", "183 cm"),
    ],
  },
  {
    id: "amk-ultralight-watertight-7",
    slug: "amk-ultralight-watertight-7",
    name: { en: "Adventure Medical Kits Ultralight/Watertight .7", ar: "حقيبة إسعاف Adventure Medical Kits Ultralight/Watertight .7" },
    brand: "Adventure Medical Kits",
    category: "camping",
    images: ["/images/products/adventure-medical-kits-ultralight-7.webp"],
    placeholder: "outfit",
    featured: false,
    isDemo: true,
    sample: true,
    sourceUrl: "https://adventuremedicalkits.com/products/ultralight-watertight-medical-kit-7",
    description: {
      en: "Waterproof first-aid kit the manufacturer sizes for 1–2 people on trips of 1–4 days. The page lists bandages, gauze, tape, moleskin, forceps, and single-use medications.",
      ar: "حقيبة إسعاف مقاومة للماء، وتحددها الشركة لشخص أو شخصين في رحلات من يوم إلى أربعة أيام. الصفحة تذكر ضمادات وشاشًا وشريطًا ولاصقًا للبثور وملقطًا وأدوية للاستعمال مرة واحدة.",
    },
    specs: [
      spec("Weight", "الوزن", "5.8 oz"),
      spec("Group size", "عدد الأشخاص", "1–2"),
      spec("Trip length", "مدة الرحلة", "1–4 days"),
    ],
  },
];
